version: '3'
##########################################################
volumes:
  prometheus_data: {}
  grafana_data: {}
##########################################################
services:
  prometheus:
    image: 'prom/prometheus:latest'
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - './prometheus:/etc/prometheus/'
      - 'prometheus_data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/promet.yml'
      - '--web.enable-admin-api'
    networks:
      testlab:
        ipv4_address: 1.1.1.10
##########################################################
  node-exporter:
    image: 'prom/node-exporter:latest'
    container_name: node-exporter
    user: root
    privileged: true
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - '9100:9100'
    networks:
      testlab:
        ipv4_address: 1.1.1.20
##########################################################
  blackbox:
    image: 'prom/blackbox-exporter:latest'
    container_name: blackbox
    volumes:
      - './prometheus/blackbox:/etc/blackbox/'
    command:
      - '--config.file=/etc/blackbox/blackbox.yml'
    ports:
      - '9115:9115'
    networks:
      testlab:
        ipv4_address: 1.1.1.30
##########################################################
  grafana:
    image: 'grafana/grafana:latest'
    container_name: grafana
    volumes:
      - 'grafana_data:/var/lib/grafana'
      - './grafana/dashboards/:/etc/grafana/dashboards'
      - './grafana/provisioning/:/etc/grafana/provisioning/'
    environment:
      - 'GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}'
      - 'GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}'
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - '3000:3000'
    networks:
      testlab:
        ipv4_address: 1.1.1.40
    depends_on:
      - prometheus
##########################################################
  ipmi-exporter:
    image: 'valdis932/ipmi-exporter:latest'
    container_name: ipmi-exporter
    restart: unless-stopped
    expose:
      - 9290
    ports:
      - '9290:9290'
    networks:
      testlab:
        ipv4_address: 1.1.1.50
    volumes:
      - './prometheus/ipmi-exporter/ipmi.yml:/etc/ipmi-exporter/ipmi.yml'
    environment: []

networks:
  testlab:
    driver: bridge
    ipam:
      config:
        - subnet: 1.1.1.0/24