global:
  scrape_interval: 5s
  
scrape_configs:
    - job_name: 'prometheus'
      static_configs: 
        - targets: ['localhost:9090']

    - job_name: 'node-exporter'
      static_configs:
        - targets: ['1.1.1.20:9100']

    - job_name: 'blackbox'
      scrape_interval: 10s
      metrics_path: /probe
      file_sd_configs:
        - files:
          - 'targets/blackbox_targets/*.yml'
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [module]
          target_label: __param_module
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: "1.1.1.30:9115"

    - job_name: 'ipmi-exporter'
      scrape_interval: 1m
      scrape_timeout: 30s
      metrics_path: /ipmi
      scheme: http
      file_sd_configs:
      - files:
        - 'targets/ipmi-targets.yml'
        refresh_interval: 5m
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [module]
          target_label: __param_module
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: "1.1.1.50:9290"
        
    - job_name: 'snmp-exporter'
      scrape_interval: 10s
      metrics_path: /snmp
      file_sd_configs:
      - files:
        - 'targets/snmp_targets/*.yml'
      params:
        module: [if_mib]
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [module]
          target_label: __param_module
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: "1.1.1.60:9116"   