devices:
  - name: test1
    address: 10.0.0.250
    user: admin
    password: qq
  - name: test2
    address: 192.168.2.1
    user: test
    password: 123
    
features:
  bgp: true
  dhcp: true
  dhcpv6: true
  dhcpl: true
  routes: true
  pools: true
  optics: true
  wlansta: true
  wlanif: true
  ipsec: true