devices:
  - name: test1
    address: 192.168.122.254
    user: admin
    password: 
    
features:
  bgp: true
  dhcp: true
  dhcpv6: true
  dhcpl: true
  routes: true
  pools: true
  optics: true
  wlansta: true
  wlanif: true
  ipsec: true